version: "3"

services:

  front:
    build: ./front
    environment:
      - debug=true
    ports:
      - 80:8080
    volumes:
      - ./front:/usr/src/front
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - 8080:8080
    entrypoint:
      - debug=true
    volumes:
      - ./front:/usr/src/backend
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/db-data
      - ./database:/etc/cron.daily
